import { projectSchema, type Project } from "@/lib/content/schemas";
import { z } from "zod";

type ProjectInput = z.input<typeof projectSchema>;

const rawProjects: ProjectInput[] = [
  {
    id: "chimera",
    name: "Chimera",
    slug: "chimera",
    description:
      "Decentralized peer-to-peer distributed computation and rendering grid in Rust.",
    longDescription:
      "Gossip discovery, QUIC mesh, Wasm sandboxing, content-addressed storage, and a distributed memory fabric — a concrete grid rather than a decentralization slide deck.",
    domains: ["systems", "infrastructure", "networking"],
    technologies: ["gossip", "QUIC", "Wasm", "content-addressed storage"],
    languages: ["Rust"],
    status: "active",
    repository: "https://github.com/theworker02/chimera",
    demo: "https://theworker02.github.io/chimera/",
    startedAt: "2026-08",
    relatedProjects: ["parallax", "stackglass", "centralizer", "deaddrop"],
    parentProjects: [],
    childProjects: [],
    featured: true,
    constellation: true,
    presentation: "chimera",
    whyExists:
      "Most distributed-compute stories assume a rented control plane. Chimera asks what happens when peers discover each other, share work without a central broker, and keep storage honest as machines come and go.",
    problem:
      "Central schedulers own the truth. Offline or adversarial environments need meshes that can still move work and verify artifacts.",
    approach:
      "Build a Rust mesh with gossip membership, QUIC transport, Wasm-bounded execution, and content-addressed results so location is not identity.",
    architecture: [
      "Gossip discovery keeps membership alive without a babysat registry",
      "QUIC mesh carries jobs between peers",
      "Wasm sandboxes bound what foreign work can do",
      "Content-addressed storage makes artifacts movable and verifiable",
      "Distributed memory fabric treats shared state as mesh-native",
    ],
    technicalDecisions: [
      "Rust for systems safety on the mesh core",
      "Wasm as the trust boundary for execution",
      "Content addressing over location-based storage",
    ],
    currentStatusNarrative:
      "Open-source systems prototype with a public GitHub Pages surface. Treat as experimental infrastructure, not a production SaaS.",
    acquisition: {
      available: true,
      types: ["individual-technology", "source-code", "strategic-collaboration"],
    },
  },
  {
    id: "parallax",
    name: "Parallax",
    slug: "parallax",
    description:
      "Polyglot migration and universal execution runtime — capture state in one language, restore in another.",
    longDescription:
      "Encode program state as language-neutral IR so workloads can migrate across language runtimes without rewriting the world.",
    domains: ["systems", "infrastructure", "developer-tools"],
    technologies: ["IR", "polyglot runtime", "state migration"],
    languages: ["Rust"],
    status: "experimental",
    repository: "https://github.com/theworker02/Parallax",
    demo: "https://theworker02.github.io/Parallax/",
    startedAt: "2026-08",
    relatedProjects: ["chimera", "centralizer", "stackglass"],
    parentProjects: [],
    childProjects: [],
    featured: true,
    constellation: true,
    presentation: "parallax",
    whyExists:
      "Language boundaries are operational boundaries. Teams pay for that every time state and execution cannot move.",
    problem:
      "Capturing running program meaning across Python, Rust, Go, JS, and Ruby usually means rewrite or brittle FFI.",
    approach:
      "Treat migration as an IR problem: capture, encode language-neutrally, restore or execute elsewhere.",
    architecture: [
      "Language frontends emit shared IR",
      "Runtime layer executes or restores IR",
      "CLI surfaces for capture and migration workflows",
    ],
    currentStatusNarrative: "Open experimental runtime with public documentation pages.",
  },
  {
    id: "stackglass",
    name: "Stackglass",
    slug: "stackglass",
    description:
      "Observability and verification layer for AI-assisted development — evidence instead of guesses.",
    domains: ["ai", "developer-tools", "systems"],
    technologies: ["MCP", "CLI", "Cursor plugin", "observability"],
    languages: ["TypeScript"],
    status: "active",
    repository: "https://github.com/theworker02/stackglass",
    demo: "https://theworker02.github.io/stackglass/",
    startedAt: "2026-08",
    relatedProjects: ["aftermath", "cartographer", "arcframe", "chimera", "parallax"],
    parentProjects: [],
    childProjects: [],
    featured: true,
    constellation: true,
    presentation: "stackglass",
    whyExists:
      "Agents write fluently and still guess about state, tests, failures, history, and contracts. Stackglass feeds them evidence.",
    problem:
      "Without an observability plane, coding agents invent repository truth from incomplete context.",
    approach:
      "Local-first evidence about state, tests, failures, configuration, contracts, and documentation — consumable by humans and agents.",
    architecture: [
      "CLI and MCP surfaces for agent tooling",
      "Evidence collection over repo and runtime signals",
      "Verification-oriented outputs for Cursor workflows",
    ],
    currentStatusNarrative: "Active open-source agent observability work.",
  },
  {
    id: "kraftverk",
    name: "Kraftverk",
    slug: "kraftverk",
    description: "Evidence-driven systems performance platform (AMD-exclusive research direction).",
    domains: ["systems", "hardware", "research"],
    technologies: ["benchmarking", "telemetry", "performance"],
    languages: ["Rust"],
    status: "research",
    repository: "https://github.com/theworker02/kraftverk",
    demo: "https://theworker02.github.io/kraftverk/",
    startedAt: "2026-08",
    relatedProjects: ["silicera", "chimera"],
    parentProjects: [],
    childProjects: [],
    featured: true,
    constellation: true,
    presentation: "kraftverk",
    whyExists:
      "Performance claims without hardware-native evidence are marketing. Kraftverk is built to measure.",
    problem: "Systems optimization often lacks reproducible, hardware-aware evidence loops.",
    approach:
      "AMD-focused performance platform combining benchmarks, telemetry, and evidence-backed optimization workflows.",
    currentStatusNarrative:
      "Research-oriented systems software. No fabricated benchmark numbers are published on this site.",
    acquisition: {
      available: true,
      types: ["individual-technology", "licensing", "strategic-collaboration"],
      notes: "AMD-exclusive research direction — discuss before assuming general portability.",
    },
  },
  {
    id: "silicera",
    name: "Silicera",
    slug: "silicera",
    description:
      "Independent systems research software for hardware-native program specialization on AMD Zen.",
    domains: ["systems", "hardware", "research"],
    technologies: ["Zen", "specialization", "systems research"],
    languages: ["Rust"],
    status: "research",
    repository: "https://github.com/theworker02/silicera",
    demo: "https://theworker02.github.io/silicera/",
    startedAt: "2026-08",
    relatedProjects: ["kraftverk"],
    parentProjects: [],
    childProjects: [],
    featured: true,
    constellation: true,
    presentation: "default",
    whyExists:
      "Generic binaries leave performance on the table when the CPU microarchitecture is known.",
    currentStatusNarrative: "Open systems research software with crates.io presence.",
  },
  {
    id: "aftermath",
    name: "Aftermath",
    slug: "aftermath",
    description:
      "Execution-backed verification layer for coding agents — durable receipts over narration.",
    domains: ["ai", "developer-tools"],
    technologies: ["verification", "CLI", "Cursor plugin", "receipts"],
    languages: ["TypeScript"],
    status: "active",
    repository: "https://github.com/theworker02/aftermath",
    demo: "https://theworker02.github.io/aftermath/",
    startedAt: "2026-08",
    relatedProjects: ["stackglass", "cartographer", "arcframe"],
    parentProjects: [],
    childProjects: [],
    featured: true,
    constellation: true,
    presentation: "omniresearch",
    whyExists:
      "Agents are persuasive. Reviewers need receipts: builds, tests, API drift, dependency changes — not self-grades.",
    problem:
      "Agent-authored code is often reviewed as prose. Confidence masquerades as evidence.",
    approach:
      "Independent examination of diffs and repo health signals, producing human- and machine-readable verification receipts.",
    architecture: [
      "Independent verification pass beside the agent",
      "Checks across build, test, lint, types, formatters, smoke, API drift",
      "Durable receipt artifacts for PR and automation consumption",
    ],
    currentStatusNarrative: "Active open-source verification tooling for agent workflows.",
  },
  {
    id: "cartographer",
    name: "Cartographer",
    slug: "cartographer",
    description:
      "TypeScript-native navigation system for software architecture — know where you are in the code.",
    domains: ["developer-tools", "ai"],
    technologies: ["tree-sitter", "static analysis", "CLI", "Cursor plugin"],
    languages: ["TypeScript"],
    status: "active",
    repository: "https://github.com/theworker02/cartographer",
    demo: "https://theworker02.github.io/cartographer/",
    startedAt: "2026-08",
    relatedProjects: ["arcframe", "stackglass", "aftermath"],
    parentProjects: [],
    childProjects: ["arcframe"],
    featured: true,
    constellation: true,
    presentation: "default",
    whyExists:
      "Editors know files. Agents know snippets. Almost nothing knows architectural place.",
    currentStatusNarrative: "Active local-first architecture navigation tooling.",
  },
  {
    id: "arcframe",
    name: "Arcframe",
    slug: "arcframe",
    description:
      "Local-first repository intelligence for Cursor MCP — graph, blast radius, evidence-backed context.",
    domains: ["ai", "developer-tools"],
    technologies: ["MCP", "graph analysis", "local-first"],
    languages: ["TypeScript", "Rust", "Go"],
    status: "active",
    repository: "https://github.com/theworker02/arcframe",
    demo: "https://theworker02.github.io/arcframe/",
    startedAt: "2026-08",
    relatedProjects: ["cartographer", "stackglass", "aftermath"],
    parentProjects: ["cartographer"],
    childProjects: [],
    featured: true,
    constellation: false,
    presentation: "default",
    currentStatusNarrative: "Local-first analysis stays on the machine.",
  },
  {
    id: "centralizer",
    name: "Centralizer",
    slug: "centralizer",
    description:
      "Go interoperability runtime that discovers, connects, and supervises software across languages.",
    domains: ["infrastructure", "systems", "developer-tools"],
    technologies: ["interop runtime", "process supervision"],
    languages: ["Go", "Python", "TypeScript"],
    status: "experimental",
    repository: "https://github.com/theworker02/centralizer",
    demo: "https://theworker02.github.io/centralizer/",
    startedAt: "2026-08",
    relatedProjects: ["parallax", "chimera"],
    parentProjects: [],
    childProjects: [],
    featured: true,
    constellation: true,
    presentation: "mesh",
  },
  {
    id: "lattice",
    name: "Lattice",
    slug: "lattice",
    description:
      "Modular physical product direction — modules that sense, decide locally, and pass useful information.",
    domains: ["hardware", "systems"],
    technologies: ["OpenCAD", "embedded sensing"],
    languages: ["JavaScript"],
    status: "experimental",
    repository: "https://github.com/theworker02/lattice",
    demo: "https://theworker02.github.io/lattice/",
    startedAt: "2026-09",
    relatedProjects: ["signalkey", "rivet"],
    parentProjects: [],
    childProjects: [],
    featured: true,
    constellation: true,
    presentation: "default",
  },
  {
    id: "patentpulse",
    name: "PatentPulse",
    slug: "patentpulse",
    description:
      "Locally owned USPTO patent corpus pipeline — stream-parse weekly dumps into SQLite and JSONL.",
    domains: ["research", "science", "ai"],
    technologies: ["datasets", "streaming parsers", "SQLite", "Hugging Face"],
    languages: ["Python"],
    status: "active",
    repository: "https://github.com/theworker02/patentpulse",
    startedAt: "2026-09",
    relatedProjects: ["atlas-of-knowledge"],
    parentProjects: [],
    childProjects: [],
    featured: true,
    constellation: true,
    presentation: "default",
    currentStatusNarrative:
      "Corpus scale is described in the repository README. This site does not invent download or training metrics.",
  },
  {
    id: "opendashcan",
    name: "OpenDashCAN",
    slug: "opendashcan",
    description:
      "Desktop CAN decode and vehicle-state research tooling for authorized logs and adapters.",
    domains: ["hardware", "systems", "research"],
    technologies: ["CAN bus", "vehicle state", "wiring research"],
    languages: ["Python"],
    status: "experimental",
    repository: "https://github.com/theworker02/OpenDashCAN",
    startedAt: "2026-09",
    relatedProjects: ["svie", "loomforge"],
    parentProjects: [],
    childProjects: [],
    featured: true,
    constellation: true,
    presentation: "default",
  },
  {
    id: "commons",
    name: "COMMONS",
    slug: "commons",
    description:
      "API-first social and coordination network for autonomous software agents.",
    domains: ["ai", "infrastructure"],
    technologies: ["Cloudflare Workers", "agent coordination", "verification"],
    languages: ["JavaScript"],
    status: "experimental",
    repository: "https://github.com/theworker02/commons",
    demo: "https://commons.matthewlooney5.workers.dev/",
    startedAt: "2026-08",
    relatedProjects: ["aftermath", "stackglass"],
    parentProjects: [],
    childProjects: [],
    featured: true,
    constellation: true,
    presentation: "mesh",
  },
  {
    id: "rivet",
    name: "Rivet",
    slug: "rivet",
    description:
      "Safety-first adaptive robot runtime for Raspberry Pi — provenance, safety, auditable competence.",
    domains: ["hardware", "systems", "science"],
    technologies: ["robotics runtime", "safety", "provenance"],
    languages: ["Python"],
    status: "experimental",
    repository: "https://github.com/theworker02/rivet",
    demo: "https://theworker02.github.io/rivet/",
    startedAt: "2026-08",
    relatedProjects: ["lattice", "signalkey"],
    parentProjects: [],
    childProjects: [],
    featured: true,
    constellation: false,
    presentation: "default",
  },
  {
    id: "deadwire",
    name: "Deadwire",
    slug: "deadwire",
    description:
      "Upstash-first recovery-intelligence control plane for DLQ incidents and provenance.",
    domains: ["infrastructure", "systems"],
    technologies: ["Upstash", "QStash", "control plane"],
    languages: ["TypeScript"],
    status: "proprietary",
    repository: "https://github.com/theworker02/deadwire",
    demo: "https://theworker02.github.io/deadwire/",
    startedAt: "2026-09",
    relatedProjects: ["reprise", "stateful-deployments-engine"],
    parentProjects: [],
    childProjects: [],
    featured: true,
    constellation: false,
    presentation: "default",
    acquisition: {
      available: true,
      types: ["individual-technology", "ip-transfer", "source-code", "licensing"],
      notes: "Proprietary pre-acquisition framing — see repository license.",
    },
  },
  {
    id: "reprise",
    name: "Reprise",
    slug: "reprise",
    description:
      "Local-first recovery and compatibility control plane for changing backends.",
    domains: ["infrastructure", "systems"],
    technologies: ["Neon", "recovery", "compatibility"],
    languages: ["TypeScript"],
    status: "proprietary",
    repository: "https://github.com/theworker02/reprise",
    demo: "https://theworker02.github.io/reprise/",
    startedAt: "2026-09",
    relatedProjects: ["deadwire"],
    parentProjects: [],
    childProjects: [],
    featured: false,
    constellation: false,
    presentation: "default",
    acquisition: {
      available: true,
      types: ["individual-technology", "source-code", "licensing"],
    },
  },
  {
    id: "deaddrop",
    name: "DeadDrop",
    slug: "deaddrop",
    description: "Encrypted delay-tolerant networking for machines rarely online together.",
    domains: ["networking", "systems"],
    technologies: ["DTN", "encryption", "protocols"],
    languages: ["Rust"],
    status: "experimental",
    repository: "https://github.com/theworker02/deaddrop",
    demo: "https://theworker02.github.io/deaddrop/",
    startedAt: "2026-08",
    relatedProjects: ["chimera"],
    parentProjects: [],
    childProjects: [],
    featured: false,
    constellation: false,
    presentation: "default",
  },
  {
    id: "atlas-of-knowledge",
    name: "Atlas of Knowledge",
    slug: "atlas-of-knowledge",
    description:
      "Machine-readable map of university knowledge with auditable provenance.",
    domains: ["research", "science", "ai"],
    technologies: ["knowledge graphs", "Hugging Face datasets"],
    languages: ["Python"],
    status: "research",
    repository: "https://github.com/theworker02/atlas-of-knowledge",
    demo: "https://theworker02.github.io/atlas-of-knowledge/",
    startedAt: "2026-08",
    relatedProjects: ["patentpulse"],
    parentProjects: [],
    childProjects: [],
    featured: false,
    constellation: false,
    presentation: "default",
  },
  {
    id: "signalkey",
    name: "SignalKey",
    slug: "signalkey",
    description:
      "Local-first desktop workflow controller with a tactile hardware direction.",
    domains: ["hardware", "developer-tools"],
    technologies: ["desktop companion", "hardware concept"],
    languages: ["TypeScript", "Python", "C"],
    status: "experimental",
    repository: "https://github.com/theworker02/signalkey",
    startedAt: "2026-09",
    relatedProjects: ["lattice", "rivet"],
    parentProjects: [],
    childProjects: [],
    featured: false,
    constellation: false,
    presentation: "default",
  },
  {
    id: "svie",
    name: "SVIE",
    slug: "svie",
    description:
      "OEM engineering package concepts for supercritical flash fuel delivery and related drivetrain ideas — code and specs, not slideware.",
    domains: ["hardware", "research"],
    technologies: ["automotive engineering", "OEM package"],
    languages: ["Python"],
    status: "proprietary",
    repository: "https://github.com/theworker02/SVIE-concept",
    demo: "https://theworker02.github.io/SVIE-concept/",
    startedAt: "2026-09",
    relatedProjects: ["opendashcan"],
    parentProjects: [],
    childProjects: [],
    featured: false,
    constellation: false,
    presentation: "default",
    acquisition: {
      available: true,
      types: ["ip-transfer", "source-code", "licensing"],
    },
  },
  {
    id: "stateful-deployments-engine",
    name: "Stateful Deployments Engine",
    slug: "stateful-deployments-engine",
    description:
      "Transactional cutover engine for volume-backed workloads. Independent — not affiliated with Railway.",
    domains: ["infrastructure", "systems"],
    technologies: ["deployments", "transactional cutover"],
    languages: ["Go", "Python", "JavaScript"],
    status: "proprietary",
    repository: "https://github.com/theworker02/stateful-deployments-engine",
    demo: "https://theworker02.github.io/stateful-deployments-engine/",
    startedAt: "2026-09",
    relatedProjects: ["deadwire", "reprise"],
    parentProjects: [],
    childProjects: [],
    featured: false,
    constellation: false,
    presentation: "default",
    acquisition: {
      available: true,
      types: ["individual-technology", "ip-transfer", "source-code"],
    },
  },
  {
    id: "bootprint",
    name: "Bootprint",
    slug: "bootprint",
    description:
      "Ruby runtime fingerprint and environment compatibility diagnostic.",
    domains: ["developer-tools"],
    technologies: ["diagnostics", "policy"],
    languages: ["Ruby"],
    status: "active",
    repository: "https://github.com/theworker02/bootprint",
    demo: "https://theworker02.github.io/bootprint/",
    startedAt: "2026-08",
    relatedProjects: [],
    parentProjects: [],
    childProjects: [],
    featured: false,
    constellation: false,
    presentation: "default",
  },
  {
    id: "bytesize",
    name: "bytesize",
    slug: "bytesize",
    description: "Parse, format, and convert human byte sizes (SI and IEC).",
    domains: ["developer-tools"],
    technologies: ["npm package"],
    languages: ["JavaScript"],
    status: "active",
    repository: "https://github.com/theworker02/bytesize",
    demo: "https://theworker02.github.io/bytesize/",
    startedAt: "2026-08",
    relatedProjects: ["cidrhas", "commitlint-lite"],
    parentProjects: [],
    childProjects: [],
    featured: false,
    constellation: false,
    presentation: "default",
  },
];

export const projects: Project[] = rawProjects.map((p) => projectSchema.parse(p));

export function getProject(slug: string) {
  return projects.find((p) => p.slug === slug);
}

export function getFeaturedProjects() {
  return projects.filter((p) => p.featured).sort((a, b) => a.name.localeCompare(b.name));
}

export function getConstellationProjects() {
  return projects.filter((p) => p.constellation);
}

export function getRelatedProjects(project: Project) {
  return project.relatedProjects
    .map((id) => projects.find((p) => p.id === id))
    .filter(Boolean) as Project[];
}
